import type { Metadata } from "next";
import React from "react";
import { Poppins } from "next/font/google";
import "./globals.css";
import {Toaster} from "react-hot-toast";
import {CommandMenu} from "@/components/command-menu";

const inter = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Toaster />
      <CommandMenu />
      {children}
      </body>
    </html>
  );
}
